name: Generate resume
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate_pdf:
    name: Generate resume
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install
          yarn compile
